//--------------------------------------------------------------------------------
// Auto-generated by LiteX (a429e85d0) on 2025-10-29 11:13:40
//--------------------------------------------------------------------------------
#ifndef __GENERATED_MEM_H
#define __GENERATED_MEM_H

#ifndef STREAMER_MEM_BASE
#define STREAMER_MEM_BASE 0x40100000L
#define STREAMER_MEM_SIZE 0x00000400
#endif

#ifndef RECORDER_MEM_BASE
#define RECORDER_MEM_BASE 0x40200000L
#define RECORDER_MEM_SIZE 0x00000400
#endif

#ifndef CSR_BASE
#define CSR_BASE 0x00000000L
#define CSR_SIZE 0x00010000
#endif

#ifndef MEM_REGIONS
#define MEM_REGIONS "STREAMER_MEM  0x40100000 0x400 \nRECORDER_MEM  0x40200000 0x400 \nCSR           0x00000000 0x10000 "
#endif
#endif
